describe('Efetuar compra no site da Nerdstore', () => {

  it('Incluir item 1 no carrinho', () => {
    cy.visit('https://nerdstore.com.br/')
    cy.get('#search').type("O Hobbit{enter}")
    cy.get('.lgpd-container__trigger').click()
    cy.scrollTo("bottom")
    cy.scrollTo("center")
    cy.get('.post-699705 > .woocommerce-LoopProduct-link > .product__thumbnail > .product__thumbnail__secondary-image > img').click()
    cy.get('.flex-control-nav > :nth-child(2) > img').click()
    cy.scrollTo(0, 300)
    cy.get(':nth-child(2) > .button').click()
    cy.get('.error').should("be.visible").and("contain", "Digite seu CEP")
    cy.get('#zipcode').type("88840000")
    cy.get(':nth-child(2) > .button').click()
    cy.get('small').should("contain", "Urussanga/SC")
    cy.get('.single_add_to_cart_button_ajax').click()
    cy.get('.header-desktop__main__menu').click()
    cy.get('.nav-mobile__menu__category--camisetas > .nav-mobile__menu__category__label').click()
    cy.get('.nav-mobile__menu__category--camisetas > .nav-mobile__menu__category__subitems > :nth-child(4) > a').click()
    cy.scrollTo(0,200)
    cy.get('.woocommerce-widget-layered-nav-list > :nth-child(4) > a').click()
    cy.get('.orderby').select("Ordenar por mais recente")
    cy.get('#search').type("star wars{enter}")
    cy.get('.post-768990 > .woocommerce-LoopProduct-link > .product__thumbnail > .product__thumbnail__secondary-image > img').click()
    cy.scrollTo("top")
    cy.scrollTo(0, 300)
    cy.get('#quantity_64bc2c860827a').clear() 
    cy.get('#quantity_64bc2c860827a').type(200)
    cy.get('.single_add_to_cart_button').click()
    cy.get('.variation-selection-needed-alert').should("be.visible").and("contain", "Primeiro, selecione o tamanho ou modelo do produto que deseja comprar")
    cy.scrollTo("top")
    cy.get(':nth-child(5) > .swatch').click()
    cy.get('.header-desktop__main__logo').click()
  })


})